
/***************************************

       PROGRAMA MONITOR NESTOR
           NOVA ELETRONICA
    SAO PAULO S.P. 01/84 MSCS/JRP
            Digitado por
          Fábio Belavenuto
            em 27/11/2012

***************************************/

/***************************************

 Endereços do monitor para serem usados
 em softwares utilitários incluindo
 este arquivo

***************************************/

RESET		= 0000h
VARR		= 0096h
REST		= 00A2h
TEMPO		= 00AFh
AJCOL		= 00C3h
AJTEC		= 00DEh
DISPLAY		= 0176h
FORMAT		= 018Eh
